**Note : Write the observation for all the statistical/viz operation you do.**

	1. Load the data
	2. Visualize the data in the dataframe
	3. Check the datatype of the columns in the dataset.
	4. Create the list of the string and numerical columns.
	5. Do the statistical check using describe functions.
	6. Check for any null values if exists fill the null values by appropriate value in using statistical analysis.
	7. If data column exists in your data, create more columns like ( day, month, year, quarter, etc. )
	8. Do the value counts of each column and short list the categorical columns.
	9. Check for outliers, if necessary filter the outliers from the data.
	10. Apply pandas function like 
		a. Type casting
		b. Filling null values.
		c. Apply lambda function
		d. Grouping ( groupby function )
		e. Pivot Table
	11. Star with Visualization part.
		a. Bar graph
		b. Line Graph
		c. Heatmap
		d. Correlation plot
		e. Histogram
		f. Pie Chart
		g. Box Plot
		h. Violin plot.
		i. Pair plot
 a. Bar graph
    b. Line Graph
    c. Heatmap
    d. Correlation plot
    e. Histogram
    f. Pie Chart
    g. Box Plot
    h. Violin plot.
    i. Pair plot

# Libraries

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #data Visualization
import seaborn as sns #data Visualization
import plotly.io as pio

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# DataSet

In [ ]:
df=pd.read_csv("../input/nifty50-stocks-dataset/National_Stock_Exchange_of_India_Ltd.csv")
df



# **Lets underastand the data, We have these colums**

*     symbol = stocks names of nifty 50
*     Open=Open price for current day
*     High=Price made high for current day
*     Low=Price made low for current day
*     Chng=Change in rupees
*     % Chng=Percentage of change from previous day close
*     Volume (lacs)=Traded volume
*     Turnover (crs.)=Turnover
*     52w H=Stock 52 week high price
*     52w L=Stock 52 week low price
*     365 d % chng=Stock price percentage change from one year
*     30 d % chng=Stock price percentage change from last 30days

# DataTypes

In [ ]:
df.dtypes

Check for null values

Changing Object type of (Open, High, Low,LTP) to float

# Type Casting

In [ ]:
df['Open'] = df['Open'].str.replace(',','')
df['Open'] = df['Open'].astype(float)

df['High'] = df['High'].str.replace(',','')
df['High'] = df['High'].astype(float)

df['Low'] = df['Low'].str.replace(',','')
df['Low'] = df['Low'].astype(float)

df['LTP'] = df['LTP'].str.replace(',','')
df['LTP'] = df['LTP'].astype(float)

df['Turnover (crs.)'] = df['Turnover (crs.)'].str.replace(',','')
df['Turnover (crs.)'] = df['Turnover (crs.)'].astype(float)

df['52w H'] = df['52w H'].str.replace(',','')
df['52w H'] = df['52w H'].astype(float)

df['52w L'] = df['52w L'].str.replace(',','')
df['52w L'] = df['52w L'].astype(float)

In [ ]:
df

# Information of DataSet

In [ ]:
df.info()

Here we conclude that we converted 'object' Dtype columns into 'Float' Dtype columns

# Create the list of the string and numerical columns.

In [ ]:
num_cols=df.select_dtypes(exclude=['object']).columns
num_cols

In [ ]:
str_cols=df.select_dtypes(exclude=['float']).columns
str_cols

Here we made the list of Numerical columns & String columns

In [ ]:
df.describe()

In [ ]:
df.isna().sum()

There is No Null Values in the Dataset.

In [ ]:
for col in num_cols:
    print("Column : ", col)
    print(f"Value counts of {col}: ",df[col].value_counts().sum())
    print(f"Number of Unique Values in {col}: ",df[col].nunique())
    print()

In [ ]:
for cols in str_cols:
    print("Column : ", cols)
    print(f"Value counts of {cols}: ",df[cols].value_counts().sum())
    print(f"Number of Unique Values in {cols}: ",df[cols].nunique())
    print()

Value counts of Numerical columns,String columns & Number of Unique Values for each column

# BoxPlot Visualization

In [ ]:
for col in num_cols:
    #print("Column : ", col)
    plt.figure()   # plots figure for each iteration
    plt.boxplot(df[col])
    plt.title(col)

> *** Checking the outliers by ploting Box Plot ***

# PairPlot Visualization

In [ ]:
sns.pairplot(df)

# BarPlot Visualization

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = df, x = 'Symbol', y = '30 d % chng')
plt.show

 **Plotting BarPlot, we can find that majority of the companies have shown negative returns if stayed invested for a month in it.**
 
 **Hence investment period should be more than a month.**

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = df, x = 'Symbol', y = '365 d % chng')
plt.show

 **Plotting BarPlot, we can find that majority of the companies have shown atleast 10% returns if stayed invested for a year in it**

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = df, x = 'Symbol', y = 'Chng')
plt.show

**On the day for which the data is recorded, we can see that majority of the companies gave negative returns**

In [ ]:
df[(df['Chng']>0)]

plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = df[(df['Chng']>0)], x = 'Symbol', y = 'Chng')
plt.show

**On the day for which the data is recorded, only 4 companies gave positive returns**

In [ ]:
bank_df = df['Symbol'].isin(['AXISBANK','HDFCBANK','ICICIBANK','INDUSINDBK','KOTAKBANK','SBIN','HDFC','BAJAJFINSV','BAJFINANCE','HDFCLIFE'])
bank_table = df[bank_df].pivot_table(values =['Open','High','Low','LTP','Chng','Volume (lacs)','52w H','52w L','Turnover (crs.)','365 d % chng','30 d % chng'], index= ['Symbol'])
bank_table.reset_index( inplace=True)
bank_table

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)

sns.barplot(data = bank_table, x = 'Symbol', y = '365 d % chng', palette='Blues_d')

plt.xlabel("Symbol")  
plt.ylabel('% Change in a Year')  
plt.title("Yearly Growth")  

plt.show

**BajajFinsv, BajajFinance,IciciBank,SBIN outperformed in Banking sector, giving more than 40% returns in a Year**

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = bank_table, x = 'Symbol', y = '30 d % chng',palette='mako')

**AxisBank and IndusInd Bank are the worst performers with more than 20% loss of the investors in a single month.**

In [ ]:
sort_yearly=df.sort_values('365 d % chng')
sort_yearly

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.barplot(data = sort_yearly, x = 'Symbol', y = '365 d % chng')
plt.xlabel("Symbol")  
plt.ylabel('% Change in a Year(Sorted)')  
plt.title("Yearly Growth(Sorted)")  
plt.show

****TataMotors gave the highest returns in a year, more than 167.95%****

****HeroMotoCo gave the lowest returns in a year, less than -16.02%****

In [ ]:
plt.figure(figsize=(15,7))
plt.xticks(rotation=90)


sns.lineplot(data = sort_yearly, x = 'Symbol', y = '365 d % chng')
plt.xlabel("Symbol")  
plt.ylabel('% Change in a Year(Sorted)')  
plt.title("Yearly Growth(Sorted)")  
plt.show

In [ ]:
df.plot.scatter(x='Open',y='365 d % chng')

In [ ]:
df.corr()

# Heatmap of DataSet

In [ ]:
nifty_50=df.iloc[:,5:]

nifty_50_corr=nifty_50.corr()
plt.figure(figsize=(10, 10))
sns.heatmap(nifty_50_corr,annot=True)
plt.title("Heatmap of Attributes to check the correlation")

**Current Percent Change has positive correlation with 30 day percent change whereas negative correlation beween 365 percentage change. That means 365 percent change does not drive the actual price but near term change affects the price.**

# Pair Plot

In [ ]:
sns.pairplot(df)

In [ ]:
f = plt.figure(figsize = (20, 20))
plt.matshow(df.corr(), fignum = f.number)
plt.xticks(range(df.select_dtypes(['number']).shape[1]), df.select_dtypes(['number']).columns, rotation=90)
plt.yticks(range(df.select_dtypes(['number']).shape[1]), df.select_dtypes(['number']).columns)
plt.show()

**Co-relation Plot**

# Pie Chart

In [ ]:
bank_table.plot.pie(x='Symbol',y='Volume (lacs)')